# Generated by Django 3.2.8 on 2021-10-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0005_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
