# Generated by Django 3.2.8 on 2021-10-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='question_id',
        ),
    ]
