# Generated by Django 3.2.8 on 2021-10-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0006_delete_department'),
        ('tree', '0002_auto_20211022_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='question_id',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionApp.question', verbose_name='关联实验'),
        ),
    ]
