# Generated by Django 3.2.8 on 2021-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_department_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='question_id',
            new_name='question',
        ),
    ]
