# Generated by Django 2.2 on 2021-10-24 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0004_rename_question_id_department_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='正文')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tree.Department', verbose_name='节点')),
                ('tags', models.ManyToManyField(blank=True, to='tree.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '试验内容',
                'verbose_name_plural': '试验内容',
            },
        ),
    ]
