# Generated by Django 2.2 on 2021-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20211024_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='body',
            field=models.TextField(default='123', verbose_name='正文'),
        ),
    ]
