# Generated by Django 2.2 on 2021-10-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_alter_node_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='File_path',
            field=models.CharField(max_length=256, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='node',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
    ]
