# Generated by Django 2.2 on 2021-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20211026_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='File_name',
            field=models.CharField(max_length=128, null=True, verbose_name='文件名'),
        ),
    ]
