# Generated by Django 2.2 on 2021-10-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0013_auto_20211029_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefile',
            name='department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='tree.Department', verbose_name='节点'),
        ),
    ]
