# Generated by Django 2.2 on 2021-10-29 04:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_nodefile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
