# Generated by Django 2.2 on 2021-10-29 11:29

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_auto_20211029_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='body',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
        ),
    ]
